spring.datasource.url=
allowPublicKeyRetrieval=true
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=

spring.jackson.time-zone=

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


stockeasy.jwt.secret=